import type { RegistrationSectionDTO } from "./apiTypes";

export function getMockRegistrationSections(): RegistrationSectionDTO[] {
  return [
    {
      id: "sec_CSCI-101-A",
      courseName: "Intro to Computer Science",
      sectionId: "CSCI-101-A",
      department: "CSCI",
      credits: 3,
      instructor: "Prof. Nguyen",
      timeSlots: [
        { day: "Mon", start: "10:00", end: "11:15" },
        { day: "Wed", start: "10:00", end: "11:15" },
      ],
      seatsAvailable: 6,
      initialStatus: "ENROLLED",
    },
    {
      id: "sec_CSCI-101-B",
      courseName: "Intro to Computer Science",
      sectionId: "CSCI-101-B",
      department: "CSCI",
      credits: 3,
      instructor: "Prof. Nguyen",
      timeSlots: [
        { day: "Tue", start: "14:00", end: "15:15" },
        { day: "Thu", start: "14:00", end: "15:15" },
      ],
      seatsAvailable: 2,
    },
    {
      id: "sec_CSCI-201-A",
      courseName: "Data Structures",
      sectionId: "CSCI-201-A",
      department: "CSCI",
      credits: 4,
      instructor: "Prof. Lang",
      timeSlots: [
        { day: "Mon", start: "11:30", end: "12:45" },
        { day: "Wed", start: "11:30", end: "12:45" },
      ],
      seatsAvailable: 0,
    },
    {
      id: "sec_CSCI-210-A",
      courseName: "Computer Organization",
      sectionId: "CSCI-210-A",
      department: "CSCI",
      credits: 3,
      instructor: "Prof. Ito",
      timeSlots: [{ day: "Fri", start: "09:00", end: "11:30" }],
      seatsAvailable: 4,
    },
    {
      id: "sec_MATH-220-B",
      courseName: "Discrete Mathematics",
      sectionId: "MATH-220-B",
      department: "MATH",
      credits: 4,
      instructor: "Prof. Patel",
      timeSlots: [
        { day: "Tue", start: "09:30", end: "10:45" },
        { day: "Thu", start: "09:30", end: "10:45" },
      ],
      seatsAvailable: 0,
      initialStatus: "WAITLISTED",
    },
    {
      id: "sec_MATH-120-A",
      courseName: "Calculus I",
      sectionId: "MATH-120-A",
      department: "MATH",
      credits: 4,
      instructor: "Prof. Stein",
      timeSlots: [
        { day: "Mon", start: "09:00", end: "10:15" },
        { day: "Wed", start: "09:00", end: "10:15" },
      ],
      seatsAvailable: 1,
    },
    {
      id: "sec_MATH-120-B",
      courseName: "Calculus I",
      sectionId: "MATH-120-B",
      department: "MATH",
      credits: 4,
      instructor: "Prof. Stein",
      timeSlots: [
        { day: "Tue", start: "12:30", end: "13:45" },
        { day: "Thu", start: "12:30", end: "13:45" },
      ],
      seatsAvailable: 5,
    },
    {
      id: "sec_ENGL-305-C",
      courseName: "Writing Seminar",
      sectionId: "ENGL-305-C",
      department: "ENGL",
      credits: 3,
      instructor: "Prof. Rivera",
      timeSlots: [{ day: "Mon", start: "10:30", end: "11:45" }],
      seatsAvailable: 2,
    },
    {
      id: "sec_ENGL-210-A",
      courseName: "Literature and Society",
      sectionId: "ENGL-210-A",
      department: "ENGL",
      credits: 3,
      instructor: "Prof. Grant",
      timeSlots: [
        { day: "Tue", start: "10:00", end: "11:15" },
        { day: "Thu", start: "10:00", end: "11:15" },
      ],
      seatsAvailable: 0,
    },
    {
      id: "sec_HIST-410-D",
      courseName: "Modern World History",
      sectionId: "HIST-410-D",
      department: "HIST",
      credits: 3,
      instructor: "Prof. Chen",
      timeSlots: [{ day: "Fri", start: "13:00", end: "14:15" }],
      seatsAvailable: 1,
    },
    {
      id: "sec_HIST-101-A",
      courseName: "World Civilizations",
      sectionId: "HIST-101-A",
      department: "HIST",
      credits: 3,
      instructor: "Prof. Martinez",
      timeSlots: [
        { day: "Mon", start: "15:30", end: "16:45" },
        { day: "Wed", start: "15:30", end: "16:45" },
      ],
      seatsAvailable: 8,
    },
    {
      id: "sec_BIOL-101-A",
      courseName: "General Biology",
      sectionId: "BIOL-101-A",
      department: "BIOL",
      credits: 4,
      instructor: "Prof. Khan",
      timeSlots: [
        { day: "Tue", start: "08:30", end: "09:45" },
        { day: "Thu", start: "08:30", end: "09:45" },
      ],
      seatsAvailable: 3,
    },
    {
      id: "sec_CHEM-121-A",
      courseName: "General Chemistry",
      sectionId: "CHEM-121-A",
      department: "CHEM",
      credits: 4,
      instructor: "Prof. Alvarez",
      timeSlots: [
        { day: "Mon", start: "13:00", end: "14:15" },
        { day: "Wed", start: "13:00", end: "14:15" },
      ],
      seatsAvailable: 0,
    },
  ];
}

