"use client";

import { useMemo, useRef, useState, type FormEvent } from "react";

type ChatRole = "student" | "instructor";

type ChatMsg = {
  id: string;
  from: "user" | "assistant";
  text: string;
  groundedInVectorDb?: boolean;
  usedLlmFallback?: boolean;
};

function uid() {
  return `${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 8)}`;
}

export default function ChatPanel(props: { role?: ChatRole }) {
  const role: ChatRole = props.role === "instructor" ? "instructor" : "student";
  const [messages, setMessages] = useState<ChatMsg[]>(() => [
    {
      id: uid(),
      from: "assistant",
      text: "Ask me anything about College0. If I can’t find it in local data yet, I’ll answer generally and label it as potentially inaccurate.",
      groundedInVectorDb: true,
      usedLlmFallback: false,
    },
  ]);
  const [pending, setPending] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const inputRef = useRef<HTMLTextAreaElement | null>(null);

  const lastAssistantMeta = useMemo(() => {
    for (let i = messages.length - 1; i >= 0; i--) {
      const m = messages[i];
      if (m.from === "assistant") return m;
    }
    return null;
  }, [messages]);

  async function onSubmit(e: FormEvent) {
    e.preventDefault();
    if (pending) return;
    setError(null);
    const text = (inputRef.current?.value ?? "").trim();
    if (!text) return;

    const userMsg: ChatMsg = { id: uid(), from: "user", text };
    setMessages((prev) => [...prev, userMsg]);
    if (inputRef.current) inputRef.current.value = "";

    setPending(true);
    try {
      const res = await fetch("/api/assistant/chat", {
        method: "POST",
        headers: { "Content-Type": "application/json", Accept: "application/json" },
        body: JSON.stringify({ message: text, role }),
      });

      const payload = await res.json().catch(() => null);
      if (!res.ok) {
        setError(payload?.message || "AI service error. Try again.");
        return;
      }

      const replyText = typeof payload?.reply === "string" ? payload.reply : "";
      const groundedInVectorDb = Boolean(payload?.groundedInVectorDb);
      const usedLlmFallback = Boolean(payload?.usedLlmFallback);

      if (!replyText.trim()) {
        setError("AI returned an empty response. Try again.");
        return;
      }

      const assistantMsg: ChatMsg = {
        id: uid(),
        from: "assistant",
        text: replyText.trim(),
        groundedInVectorDb,
        usedLlmFallback,
      };
      setMessages((prev) => [...prev, assistantMsg]);
      requestAnimationFrame(() => inputRef.current?.focus());
    } catch {
      setError("Network error. Try again.");
    } finally {
      setPending(false);
    }
  }

  return (
    <section className="rounded-2xl bg-white border border-black/5 shadow-sm overflow-hidden">
      <div className="px-5 py-4 border-b border-black/5 flex items-center justify-between gap-3">
        <div>
          <div className="text-sm font-semibold text-slate-900">AI Q&amp;A</div>
          <div className="text-[11px] text-slate-500">Vector DB first → Gemini fallback (for now).</div>
        </div>
        <span className="text-[11px] font-semibold rounded-full bg-slate-100 px-2.5 py-1 text-slate-700">
          {role}
        </span>
      </div>

      <div className="p-4 space-y-3 max-h-[380px] overflow-auto">
        {messages.map((m) => {
          const isUser = m.from === "user";
          const showDisclaimer = !isUser && (m.usedLlmFallback || m.groundedInVectorDb === false);
          return (
            <div key={m.id} className={isUser ? "flex justify-end" : "flex justify-start"}>
              <div
                className={[
                  "max-w-[92%] rounded-2xl px-3.5 py-2.5 text-sm leading-relaxed",
                  isUser
                    ? "bg-neutral-900 text-white"
                    : "bg-slate-50 text-slate-900 border border-slate-100",
                ].join(" ")}
              >
                <div className="whitespace-pre-wrap">{m.text}</div>
                {showDisclaimer ? (
                  <div className="mt-2 text-[11px] text-slate-500">
                    This answer was generated by a general AI and may contain inaccuracies.
                  </div>
                ) : null}
              </div>
            </div>
          );
        })}
      </div>

      <div className="px-4 pb-4">
        {error ? (
          <div className="mb-3 rounded-xl border border-red-200 bg-red-50 px-3 py-2 text-xs text-red-800" role="alert">
            {error}
          </div>
        ) : null}

        <form onSubmit={onSubmit} className="flex items-end gap-2">
          <textarea
            ref={inputRef}
            rows={2}
            placeholder="Ask a question…"
            className="flex-1 resize-none rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm text-slate-900 placeholder:text-slate-400 focus:outline-none focus:ring-2 focus:ring-[#F07E62]/25 focus:border-[#F07E62]/50"
            disabled={pending}
          />
          <button
            type="submit"
            disabled={pending}
            className="inline-flex items-center justify-center rounded-xl bg-[#F07E62] px-4 py-2.5 text-sm font-semibold text-white shadow-[0_12px_22px_rgba(240,126,98,0.35)] transition hover:brightness-[0.97] active:brightness-[0.95] disabled:opacity-60"
          >
            {pending ? "Sending…" : "Send"}
          </button>
        </form>

        {lastAssistantMeta && (lastAssistantMeta.usedLlmFallback || lastAssistantMeta.groundedInVectorDb === false) ? (
          <div className="mt-2 text-[11px] text-slate-500">
            Tip: once RAG is wired, grounded answers won’t show this disclaimer.
          </div>
        ) : null}
      </div>
    </section>
  );
}

